#server:
#  port: 8761 # Indicate the default PORT where this service will be started
#
#eureka:
#  client:
#    registerWithEureka: false   #telling the server not to register himself in the service registry
#    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
#
#spring:
#  profiles:
#  active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///src//main//resources

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file:///src//main//resources
  application:
    name: eureka-server